<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MadiunUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            ['firstname' => "Chayara Alima Z M", 'email' => "alyamahdini22@gmail.com", 'username' => "alyamahdini22@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HARYADI PRAWIRO", 'email' => "haryadiprawiro55@gmail.com", 'username' => "haryadiprawiro55@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NURIN CHASANAH", 'email' => "muhammadzahroni93@gmail.com", 'username' => "muhammadzahroni93@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DIDIK PRASETYO", 'email' => "usopkun003@gmail.com", 'username' => "usopkun003@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SIGRA TRISNAWATI", 'email' => "sigrashezhe@gmail.com", 'username' => "sigrashezhe@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PRIYO TEGAR NUGROHO", 'email' => "priyotegarnugroho12@gmail.com", 'username' => "priyotegarnugroho12@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "TINA LIA SUGIANA", 'email' => "tinaliasugiana@gmail.com", 'username' => "tinaliasugiana@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PRASETYO BUDI UTOMO", 'email' => "pbuketawang102017@gmail.com", 'username' => "pbuketawang102017@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Bambang supriyanto", 'email' => "bambangpriyo74@gmail.com", 'username' => "bambangpriyo74@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "MARATU SHOLIKHAH", 'email' => "maratusholikhah65@gmail.com", 'username' => "maratusholikhah65@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Silvia Jauharotul Muna", 'email' => "Silviamuna5@gmail.com", 'username' => "Silviamuna5@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RIKA AGUNG HARIJADI", 'email' => "agungharijadi22@gmail.com", 'username' => "agungharijadi22@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DINNUR MAHARIMA", 'email' => "dinnurmaharima00@gmail.com", 'username' => "dinnurmaharima00@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVITA SULYSTIYANINGRUM", 'email' => "novita.sulystiyaningrum@gmail.com", 'username' => "novita.sulystiyaningrum@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YASIN WIJAYA", 'email' => "yasinwijaya6@gmail.com", 'username' => "yasinwijaya6@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "TRI SUGIARTI", 'email' => "trisugiarti059@gmail.com", 'username' => "trisugiarti059@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVI ROCHITA", 'email' => "novirochita29@gmail.com", 'username' => "novirochita29@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUMADI", 'email' => "suromadi93@gmail.com", 'username' => "suromadi93@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUPRIATI", 'email' => "supriatisupriati86@gmail.com", 'username' => "supriatisupriati86@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SOVIEC HERNAWATI WIDYANINGRUM", 'email' => "soviec2016@gmail.com", 'username' => "soviec2016@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Arif Muhyidin", 'email' => "Arifardinta@gmail.com", 'username' => "Arifardinta@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUDARNO", 'email' => "Sudarno9784@gmail.com", 'username' => "Sudarno9784@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "WIWIT NUR ROFIN", 'email' => "andinabowo@gmail.com", 'username' => "andinabowo@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ILHAM ALIF NUR ZEHAN", 'email' => "ilhamalifnz20@gmail.com", 'username' => "ilhamalifnz20@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Kuwat Budianto", 'email' => "Markuadfuad123@gmail.com", 'username' => "Markuadfuad123@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ENDIK SUDARMAJI", 'email' => "ajiendik@gmail.com", 'username' => "ajiendik@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVITA ARINI", 'email' => "rumahdjahitvita@gmail.com", 'username' => "rumahdjahitvita@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "EDI PRASTIO", 'email' => "sriedi856@gmail.com", 'username' => "sriedi856@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "TRI RAHAYU WILUJENG", 'email' => "ryjenk93@gmail.com", 'username' => "ryjenk93@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SIGIT SUKO BISONO", 'email' => "wirayudha.wibisono@gmail.com", 'username' => "wirayudha.wibisono@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "MARYANI", 'email' => "maryaniii1612@gmail.com", 'username' => "maryaniii1612@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HERMAWAN", 'email' => "hermawan.mei25@gmail.com", 'username' => "hermawan.mei25@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Febrian Fajar Dwi Widodo", 'email' => "Febrianfajar38@gmail.com", 'username' => "Febrianfajar38@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DUMAS LUSANGAJI", 'email' => "dumasmain@gmail.com", 'username' => "dumasmain@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SRI WAHYUNI", 'email' => "yuni240777@gmail.com", 'username' => "yuni240777@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "CHRISTANTI EKA RATNASARI", 'email' => "christantidienka.92@gmail.com", 'username' => "christantidienka.92@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Eko Iswoyo", 'email' => "ekoekomadiun23@gmail.com", 'username' => "ekoekomadiun23@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DYAS PURWIDYANINGSIH", 'email' => "dyaspurwidyaningsih@gmail.com", 'username' => "dyaspurwidyaningsih@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DESI NILASARI", 'email' => "desinilasari0412@gmail.com", 'username' => "desinilasari0412@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUMARNO", 'email' => "Sumarnokuwu811@gmail.com", 'username' => "Sumarnokuwu811@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Lilik Yuniatmika", 'email' => "yuniatmikalilikg13@gmail.com", 'username' => "yuniatmikalilikg13@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NURKAMTO", 'email' => "noerae40@gmail.com", 'username' => "noerae40@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Entin indriyana", 'email' => "ntinindrya@gmail.com", 'username' => "ntinindrya@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YENI MARGIATI", 'email' => "margiyen82@gmail.com", 'username' => "margiyen82@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ali Komarudin", 'email' => "tafakkur9@gmail.com", 'username' => "tafakkur9@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DODIK WAHYU PRASETYO", 'email' => "dodikwahyu7@gmail.com", 'username' => "dodikwahyu7@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Wiwik sukowati", 'email' => "wiwiksukowati511@gmail.com", 'username' => "wiwiksukowati511@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yuni Rahmawati", 'email' => "berl1no3y@gmail.com", 'username' => "berl1no3y@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DESI PURWATI", 'email' => "desy88aja@gmail.com", 'username' => "desy88aja@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SITI NUR AFIAH", 'email' => "Afiahnur800@gmail.com", 'username' => "Afiahnur800@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FETTY KRISTIANA RAHMI", 'email' => "arrevakristiana@gmail.com", 'username' => "arrevakristiana@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "BUDI DAYA", 'email' => "boediya@gmail.com", 'username' => "boediya@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LILIS SUMIATUN", 'email' => "lilisharun5@gmail.com", 'username' => "lilisharun5@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANING RAHAYUNI", 'email' => "Aningrahayuni@gmail.com", 'username' => "Aningrahayuni@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANTOK NUGROHO", 'email' => "antok.jazznet@gmail.com", 'username' => "antok.jazznet@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANY WIDYANINGRUM", 'email' => "anywidyaningrum26@gmail.com", 'username' => "anywidyaningrum26@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Andik suryono", 'email' => "davin512181@gmail.com", 'username' => "davin512181@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUDARSO", 'email' => "Bowiebrewoxs@gmail.com", 'username' => "Bowiebrewoxs@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RUDI HARTANTO", 'email' => "hartarudi29@gmail.com", 'username' => "hartarudi29@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SRI WILUJENG", 'email' => "20sriwil@gmail.com", 'username' => "20sriwil@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RULIK MARDIYANTO", 'email' => "redmipakrt@gmail.com", 'username' => "redmipakrt@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Bachtiar Arifin", 'email' => "bachtiarmadi1@gmail.com", 'username' => "bachtiarmadi1@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ERVINA LUTVIANA", 'email' => "ervilutvi29@gmail.com", 'username' => "ervilutvi29@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dana istria wahyudi", 'email' => "Yani08982@gmail.com", 'username' => "Yani08982@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Gama Ega Satriya", 'email' => "egagama3@gmail.com", 'username' => "egagama3@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Desy Kurniawati", 'email' => "desykurniawati20@gmail.com", 'username' => "desykurniawati20@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DYAH ALIF SURYANINGSIH", 'email' => "dyahalif55@gmail.com", 'username' => "dyahalif55@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "IRAWAN", 'email' => "Ira.ramma@gmail.com", 'username' => "Ira.ramma@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SRI NUR FIAH", 'email' => "fiahnur820@gmail.com", 'username' => "fiahnur820@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "KOMARI", 'email' => "mimimaman3@gmail.com", 'username' => "mimimaman3@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Pipit dian sulistyowati", 'email' => "adzraxell82@gmail.com", 'username' => "adzraxell82@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUPARTI", 'email' => "suparti780627@gmail.com", 'username' => "suparti780627@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PANGGA RILO PAMBEKTI", 'email' => "Panggarilo0@gmail.com", 'username' => "Panggarilo0@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FEBRI ARIYANTO", 'email' => "febria182@gmail.com", 'username' => "febria182@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Tutuk darwanti", 'email' => "Tutuk8771@gmail.com", 'username' => "Tutuk8771@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SHINTYA ARIANE", 'email' => "shintyaariane@gmail.com", 'username' => "shintyaariane@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DWI LESTARI NINGSIH", 'email' => "Abiae867@gmail.co.id", 'username' => "Abiae867@gmail.co.id", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Andhik budi santoso", 'email' => "Andhik50@gmail.com", 'username' => "Andhik50@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DEWI LESTARI", 'email' => "fuadaja3@gmail.com", 'username' => "fuadaja3@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SHEITA KURNIASARI", 'email' => "sheitakurniasari38@gmail.com", 'username' => "sheitakurniasari38@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AYU FITRIYA SARI", 'email' => "Lakzaoon@gmail.com", 'username' => "Lakzaoon@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AFIFATUN NAFISAH", 'email' => "pitchuan16@gmail.com", 'username' => "pitchuan16@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yuliati", 'email' => "Yuliatiy253@gmail.com", 'username' => "Yuliatiy253@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FITRI MUSYAROFAH", 'email' => "Alifalintang.adbis@gmail.com", 'username' => "Alifalintang.adbis@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PANCA RAGIL YUASTA", 'email' => "Pancaragil87@gmail.com", 'username' => "Pancaragil87@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ETIK TRI CAHYANI", 'email' => "Iqfalathakhul@gmail.com", 'username' => "Iqfalathakhul@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PURWATI", 'email' => "purwati3519080@gmail.com", 'username' => "purwati3519080@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YUSUF FITRA KURNIAWAN", 'email' => "jagadpramudito@gmail.com", 'username' => "jagadpramudito@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANISYA CAHYANING UTAMI SETYA BUDI", 'email' => "anisyacusb@gmail.com", 'username' => "anisyacusb@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Farah Faizun", 'email' => "faizunilma07@gmail.com", 'username' => "faizunilma07@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVI RETNOWATI", 'email' => "noviretnowati91@gmail.com", 'username' => "noviretnowati91@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AMELIA PUTRI ARDIANINGRUM", 'email' => "amelia.ptr.ardianingrum@gmail.com", 'username' => "amelia.ptr.ardianingrum@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUTANTI NINGSIH", 'email' => "tantiningsih293@gmail.com", 'username' => "tantiningsih293@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yappy Kristiawan", 'email' => "aura.matahari1985@gmail.com", 'username' => "aura.matahari1985@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Efrida Cahyaningrum", 'email' => "efridacahyaningrum@gmail.com", 'username' => "efridacahyaningrum@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AULIA NISAK FAUZIAH", 'email' => "auliafauziah1005@gmail.com", 'username' => "auliafauziah1005@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SULASMI", 'email' => "sulasmimikhayla@gmail.com", 'username' => "sulasmimikhayla@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RIRIN NURYANTI", 'email' => "nuryantiririn81@gmail.com", 'username' => "nuryantiririn81@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FITRI SANDIKA", 'email' => "sandikafitri2@gmail.com", 'username' => "sandikafitri2@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "TUTUS LASMIASIH", 'email' => "tutusedi0@gmail.com", 'username' => "tutusedi0@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DWI RIAN ROSADI", 'email' => "dwirianrosadirosadi@gmail.com", 'username' => "dwirianrosadirosadi@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "WAHYU IRYANTI", 'email' => "ghea.darmaya1110@gmail.com", 'username' => "ghea.darmaya1110@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YUNI ERNAWATI", 'email' => "ernawatiyuni83@gmail.com", 'username' => "ernawatiyuni83@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Eka Wahyu Kurniasari", 'email' => "ekawahyukurniasari@gmail.com", 'username' => "ekawahyukurniasari@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ELWIYANA", 'email' => "elwiyana9@gmail.com", 'username' => "elwiyana9@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NURYANI", 'email' => "nuryani11april@gmail.com", 'username' => "nuryani11april@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SYAMSUL HUDA", 'email' => "shaqsaev@gmail.com", 'username' => "shaqsaev@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "WINARTI", 'email' => "wibycahyono28@gmail.com", 'username' => "wibycahyono28@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUHARNI", 'email' => "Harnisu335@gmail.com", 'username' => "Harnisu335@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Naning puspita sari", 'email' => "puspitananing123@gmail.com", 'username' => "puspitananing123@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "UMIATUN", 'email' => "aditya0158@gmail.com", 'username' => "aditya0158@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LAILATUL HIDAYAH", 'email' => "Lailatulhidayah1982@gmail.com", 'username' => "Lailatulhidayah1982@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yuni purwati", 'email' => "yunichan09@gmail.com", 'username' => "yunichan09@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NUVIAN TRI SETYAWAN", 'email' => "Noviants94@gmail.com", 'username' => "Noviants94@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "UMI SOLIKAH", 'email' => "umisolikah52580@gmail.com", 'username' => "umisolikah52580@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "JATI RYAN PRAMONO", 'email' => "jatiryanp@gmail.com", 'username' => "jatiryanp@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DESSI RATNASARI", 'email' => "dessiratnasari0101@gmail.com", 'username' => "dessiratnasari0101@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "GUNARSIH", 'email' => "gunnarsih25@gmail.com", 'username' => "gunnarsih25@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SITI AMINATIN", 'email' => "Sitiaminatin273@gmail.com", 'username' => "Sitiaminatin273@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Henik Susanti", 'email' => "heniksusanti91@gmail.com", 'username' => "heniksusanti91@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SITI KAMSIYAH", 'email' => "pleckenout@gmail.com", 'username' => "pleckenout@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SAWITRIYANI", 'email' => "Sawitriyani5@gmail.com", 'username' => "Sawitriyani5@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ENI DWI SUSANTI", 'email' => "enidwisusanti92@gmail.com", 'username' => "enidwisusanti92@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANNISTYA INDAH DEVA CAHAYANI", 'email' => "annistyadeva@gmail.com", 'username' => "annistyadeva@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "KUNTARI", 'email' => "Ayangputriariyanto@gmail.com", 'username' => "Ayangputriariyanto@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "JUWARINI MEININGSIH", 'email' => "juwarinimeiningsih@gmail.com", 'username' => "juwarinimeiningsih@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "BIMANTORO WAHYU RAMDHANI", 'email' => "bimantorowahyu14@gmail.com", 'username' => "bimantorowahyu14@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YUNITA FEBRIANTI EKA PUTRI", 'email' => "yunitafebrianti35@gmail.com", 'username' => "yunitafebrianti35@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YOHAN PAMUNGKAS", 'email' => "akbarisyapriskaton@gmail.com", 'username' => "akbarisyapriskaton@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yulia Ari Pertiwi", 'email' => "Pertiwiyulia55@gmail.com", 'username' => "Pertiwiyulia55@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "MIEFTA AMIRUL LATHIFAH", 'email' => "amifta.lathifah@gmail.com", 'username' => "amifta.lathifah@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Wiwik Triwidyaningsih", 'email' => "wiwiktriwidya1991@gmail.com", 'username' => "wiwiktriwidya1991@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUNARSIH", 'email' => "meymey.110411@gmail.com", 'username' => "meymey.110411@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SANTI MARETA DIANINGRUM", 'email' => "santimareta832@gmail.com", 'username' => "santimareta832@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DWI SUSENO NUGROHO", 'email' => "nugrahasemangat42@gmail.com", 'username' => "nugrahasemangat42@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SHANTI KURNIAWATI", 'email' => "shantikurniawati77@gmail.com", 'username' => "shantikurniawati77@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVA ANGGRAINI", 'email' => "novaanggraini293@gmail.com", 'username' => "novaanggraini293@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SIGID TULUS PUJIONO", 'email' => "saktiiiibima@gmail.com", 'username' => "saktiiiibima@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARIFIN NUGRAHA", 'email' => "arifinn.nugrahaa@gmail.com", 'username' => "arifinn.nugrahaa@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "IVA AL MUMTARI", 'email' => "iva.almum@gmail.com", 'username' => "iva.almum@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Saman Haryanto", 'email' => "samanharyanto578@gmail.com", 'username' => "samanharyanto578@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RANGGA RAMADHAN", 'email' => "Ranggaramadhan5758@gmail.com", 'username' => "Ranggaramadhan5758@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Subandrio", 'email' => "subandri988@gmail.com", 'username' => "subandri988@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PRIANI TRIMIARSIH", 'email' => "priti.trimi@gmail.com", 'username' => "priti.trimi@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "WAHYU SRI NURYANTI", 'email' => "wahyu210782@gmail.com", 'username' => "wahyu210782@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ALI FAHRUL NGABIT", 'email' => "Alfacaruban207@gmail.com", 'username' => "Alfacaruban207@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HENI RISTIANI", 'email' => "heniskima@gmail.com", 'username' => "heniskima@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "VENDY WAHYUDIANTO", 'email' => "vendywahyudianto38@gmail.com", 'username' => "vendywahyudianto38@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SEKAR DIAH PERMATA", 'email' => "sekardiah412@gmail.com", 'username' => "sekardiah412@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FITRI WIDYANINGRUM", 'email' => "fitwid22@gmail.com", 'username' => "fitwid22@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YESI OKTANINGTYAS", 'email' => "Oktaningtyasyesi@gmail.com", 'username' => "Oktaningtyasyesi@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUPRIANTO", 'email' => "torick.sabar01@gmail.com", 'username' => "torick.sabar01@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "GAYUH PRASTYO", 'email' => "gayuhp19@gmail.com", 'username' => "gayuhp19@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Tri Suci Prihatin Ningsih", 'email' => "tsuci373@gmail.com", 'username' => "tsuci373@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "IDA ERNAWATI", 'email' => "iedhaerna02@gmail.com", 'username' => "iedhaerna02@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Deni Rido kristiawan", 'email' => "deniridokristiawan@gmail.com", 'username' => "deniridokristiawan@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ULLI FATUL FATIMAH", 'email' => "ullifatul96@gmail.com", 'username' => "ullifatul96@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Riska Mayasari", 'email' => "kamayriska@gmail.com", 'username' => "kamayriska@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Moch.saifudin", 'email' => "syaifudin.m86@gmail.com", 'username' => "syaifudin.m86@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Natania kusuma ningrum", 'email' => "taania.chubby@gmail.com", 'username' => "taania.chubby@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Diyo oktafiano", 'email' => "diyooktafiano48@gmail.com", 'username' => "diyooktafiano48@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "WINDA WARDANA", 'email' => "windawardana1117@gmail.com", 'username' => "windawardana1117@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ZAKIYA AINUR ROHMAN", 'email' => "zakiyaainurrohman.zar@gmail.com", 'username' => "zakiyaainurrohman.zar@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Rini Wijayanti", 'email' => "riniwijayanti179@gmail.com", 'username' => "riniwijayanti179@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "IKA NURFIANA", 'email' => "nurfianaika1@gmail.com", 'username' => "nurfianaika1@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ELSHA HANIFAH", 'email' => "elshahanifah@gmail.com", 'username' => "elshahanifah@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARY KUSUMA WARDANI", 'email' => "ary.wardani03@gmail.com", 'username' => "ary.wardani03@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Purwo Jalu Setyo aji", 'email' => "purwojalu82@gmail.com", 'username' => "purwojalu82@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dyah jatu kusumaningtyas", 'email' => "Ghaziahafiza06@gmail.com", 'username' => "Ghaziahafiza06@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "VEDRI TRI LAKSONO", 'email' => "vedrixps08@gmail.com", 'username' => "vedrixps08@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HANIK NUR HIDAYAH", 'email' => "haniknur97@gmail.com", 'username' => "haniknur97@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DONNY THEO VASELLENO", 'email' => "donnytheovaselleno@gmail.com", 'username' => "donnytheovaselleno@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DINA RITA KALIMANTINI", 'email' => "dinarita98@gmail.com", 'username' => "dinarita98@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "KHOIRUL BARIYAH", 'email' => "Khoirulbariyah72@gmail.com", 'username' => "Khoirulbariyah72@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "APIDA PARASMITA", 'email' => "apidaparasmita26@gmail.com", 'username' => "apidaparasmita26@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Mamik Ratnawati", 'email' => "mamikratnawati130@gmail.com", 'username' => "mamikratnawati130@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YUHANA ASTUTI IKA MEGAWATI", 'email' => "yuhana.mega@gmail.com", 'username' => "yuhana.mega@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Lina nurhayanti", 'email' => "Linanur20481@gmail.com", 'username' => "Linanur20481@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Joko nurkolis", 'email' => "jokonurkolis79@gmail.com", 'username' => "jokonurkolis79@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SULTON MUHIBUDDIN ALWALID SYAH", 'email' => "sulton.muhibuddinas@gmail.com", 'username' => "sulton.muhibuddinas@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Endang Puspitasari", 'email' => "princesvionna@gmail.com", 'username' => "princesvionna@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Jamari", 'email' => "susukambinggo@gmail.com", 'username' => "susukambinggo@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DOVIN MURTIKASARI", 'email' => "dovinsari17@gmail.com", 'username' => "dovinsari17@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DIKHI ANDRA PUSPITA", 'email' => "Navyzhasafiya@gmail.com", 'username' => "Navyzhasafiya@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Wahyuningrum Ahzammubasharoh", 'email' => "wahyuningrum209@gmail.com", 'username' => "wahyuningrum209@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ATIKA PUTRI APRILIA", 'email' => "msatika16@gmail.com", 'username' => "msatika16@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "JIHAN SUCI LESTARI", 'email' => "Jihansuci49@gmail.com", 'username' => "Jihansuci49@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Kanifatun Nadofah", 'email' => "chanifah705@gmail.com", 'username' => "chanifah705@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ririn Dwi Corina", 'email' => "ririncorina50@gmail.com", 'username' => "ririncorina50@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "EVI YULIANA", 'email' => "Nanangwahyudi846@gmail.com", 'username' => "Nanangwahyudi846@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "GATOT SUDARSONO", 'email' => "gatotsudarsono100@gmail.com", 'username' => "gatotsudarsono100@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SILVINA NUR FADHILAH", 'email' => "silvinanur02@gmail.com", 'username' => "silvinanur02@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "APRILIA KURNIANING PUTRI", 'email' => "aprilia.kurnianing.putri@gmail.com", 'username' => "aprilia.kurnianing.putri@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dwi hartono", 'email' => "03dwihartono@gmail.com", 'username' => "03dwihartono@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NUNUNG SURYANINGSIH", 'email' => "nunung.0391@gmail.com", 'username' => "nunung.0391@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PURWANINGSIH", 'email' => "npurwa30@gmail.com", 'username' => "npurwa30@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ASIYAH TRININGRUM", 'email' => "asiyahhtriningrum@gmail.com", 'username' => "asiyahhtriningrum@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "EKA NUR SEPTYANA", 'email' => "ekanurs805@gmail.com", 'username' => "ekanurs805@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Rendra Budy Wisnu darsono", 'email' => "Rng.aak@gmail.com", 'username' => "Rng.aak@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "TITIN ANDRIANA", 'email' => "titinandriana9@gmail.com", 'username' => "titinandriana9@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yesi Ramadhani", 'email' => "yesiramadhani4@gmail.com", 'username' => "yesiramadhani4@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SALIMURRAHMAN", 'email' => "srahman.fs@gmail.com", 'username' => "srahman.fs@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "BINTI MAQDHALUL KHASANAH", 'email' => "Bintiekasha94@gmail.com", 'username' => "Bintiekasha94@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Priska Silviani", 'email' => "silvianipriska19@gmail.com", 'username' => "silvianipriska19@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YAYUK NINGSIH", 'email' => "iningraihza@gmail.com", 'username' => "iningraihza@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "UUN LIDIA PURNAWATI", 'email' => "lidiauun00@gmail.com", 'username' => "lidiauun00@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LULUK NAHDHIATUL ULFAH", 'email' => "chiloelzildud@gmail.com", 'username' => "chiloelzildud@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DWI SUMIYATI", 'email' => "dwisumiyati32@gmail.com", 'username' => "dwisumiyati32@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUMARYO", 'email' => "sumaryo.dp@gmail.com", 'username' => "sumaryo.dp@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Iva wijayanti", 'email' => "ivaw013@gmail.com", 'username' => "ivaw013@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Uthy Kemala Sari", 'email' => "uthykemala@gmail.com", 'username' => "uthykemala@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOFI KARTIKA SARI", 'email' => "kartikanofi7@gmail.com", 'username' => "kartikanofi7@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Athallari' Naufal Nalan Shafa'", 'email' => "athallarinaufal@gmail.com", 'username' => "athallarinaufal@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "BIMA ALIM AZIZI", 'email' => "alzybima@gmail.com", 'username' => "alzybima@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YULI ASTUTI", 'email' => "yukalia1228@gmail.com", 'username' => "yukalia1228@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NUTIK NURYATIN", 'email' => "nutiknuryatin836@gmail.com", 'username' => "nutiknuryatin836@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Hani'atul Mukharomah", 'email' => "haniatul93@gmail.com", 'username' => "haniatul93@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ROCHMANUL KAKIM", 'email' => "rochmanulk@gmail.com", 'username' => "rochmanulk@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Eka Yuliana Rahmawati", 'email' => "sanumazka283@gmail.com", 'username' => "sanumazka283@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Erny Setyowati", 'email' => "ernisetyowati812@gmail.com", 'username' => "ernisetyowati812@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LYTA PUSPYTASAXI", 'email' => "lytapuspytasaxi@gmail.com", 'username' => "lytapuspytasaxi@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Supri anik", 'email' => "naniknoor3@gmail.com", 'username' => "naniknoor3@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ririn susanti", 'email' => "ririnsusanti785@gmail.com", 'username' => "ririnsusanti785@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FARIDATUL MUKAROMAH", 'email' => "faridatulmukaromah33@gmail.com", 'username' => "faridatulmukaromah33@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Suparmi", 'email' => "suparmimlaten@gmail.com", 'username' => "suparmimlaten@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HANSDY DAVID IRSANTO", 'email' => "hansdydavid@gmail.com", 'username' => "hansdydavid@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LULUK AZIZAH", 'email' => "lulukazizah043@gmail.com", 'username' => "lulukazizah043@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUPIYAH", 'email' => "ulya25supiyah@gmail.com", 'username' => "ulya25supiyah@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "YULIANA PUSPA IVAWANTHIE", 'email' => "Ivasubagyo@gmail.com", 'username' => "Ivasubagyo@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Zainul Muarif", 'email' => "zainmuarif0807@gmail.com", 'username' => "zainmuarif0807@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RIDHOAJI SAMPURNO, S.PD.", 'email' => "ridhoajisampurno260693@gmail.com", 'username' => "ridhoajisampurno260693@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Wiwik handayani", 'email' => "bundawiwik81@gmail.com", 'username' => "bundawiwik81@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARIFAH NUNUNG HERMAWATI", 'email' => "arifah.a3xx@gmail.com", 'username' => "arifah.a3xx@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ALVIANA MUNADHIROTUR ROHMAH", 'email' => "alvianamr13@gmail.com", 'username' => "alvianamr13@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANISWATUL MUKOYAROH", 'email' => "aniswatul.andi@gmail.com", 'username' => "aniswatul.andi@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Erike Ramadhani", 'email' => "ramadhanierike@gmail.com", 'username' => "ramadhanierike@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Siti Rodliyah", 'email' => "rodliyahsiti1991@gmail.com", 'username' => "rodliyahsiti1991@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANDIK DWI ANDRIANSYAH", 'email' => "zivandriansyah87@gmail.com", 'username' => "zivandriansyah87@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Nuryanti anis satiti", 'email' => "nuryantianissatiti@gmail.com", 'username' => "nuryantianissatiti@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARKOM NAJEK MODIN", 'email' => "najekmodinarkom@gmail.com", 'username' => "najekmodinarkom@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AGUS SETYONO", 'email' => "setyonoagus98@gmail.com", 'username' => "setyonoagus98@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Evita Dewi Anggraini", 'email' => "Evitadewianggraini89@gmail.com", 'username' => "Evitadewianggraini89@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANDIK ARIFIN", 'email' => "Andik2262@gmail.com", 'username' => "Andik2262@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Vera Sandika Aditya Mindarto", 'email' => "Veraoh043@gmail.com", 'username' => "Veraoh043@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Lia Kusuma Wardani", 'email' => "liakusumawardani00@gmail.com", 'username' => "liakusumawardani00@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Agus Suswanto", 'email' => "ttomen77@gmail.com", 'username' => "ttomen77@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FATHU AZKA FIKRI", 'email' => "faffikri@gmail.com", 'username' => "faffikri@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "KHOIRUL HUDA", 'email' => "95.hudakhoirul@gmail.com", 'username' => "95.hudakhoirul@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Choirunnisa", 'email' => "nisanavly96@gmail.com", 'username' => "nisanavly96@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HESTI VERAWATI", 'email' => "hestiverawati25@gmail.com", 'username' => "hestiverawati25@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUMARYONO", 'email' => "hpredmi9a11152021@gmail.com", 'username' => "hpredmi9a11152021@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Maslakatus Solikah", 'email' => "maslakatussolikah@gmail.com", 'username' => "maslakatussolikah@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Novita Sari", 'email' => "novitasarireza28@gmail.com", 'username' => "novitasarireza28@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AJI RAHMAWAN", 'email' => "ajirahmawan01@gmail.com", 'username' => "ajirahmawan01@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ALPIKA WIJAYANTI", 'email' => "Wijayantialpika02@gmail.com", 'username' => "Wijayantialpika02@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ISTIQOMAH", 'email' => "istisafa678@gmail.com", 'username' => "istisafa678@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Susi Nur Aprilia", 'email' => "Aprlsusinurnew@gmail.com", 'username' => "Aprlsusinurnew@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NADIA ANGGELINA MARGARETA", 'email' => "nadiagaret4@gmail.com", 'username' => "nadiagaret4@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVITA AYU AMALIA", 'email' => "Novitaayu202@gmail.com", 'username' => "Novitaayu202@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Budiyono", 'email' => "adwi39314@gmail.com", 'username' => "adwi39314@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ROSI NOVITASARI", 'email' => "rosi.novitasari1511@gmail.com", 'username' => "rosi.novitasari1511@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "CICIK MISWOROWATI", 'email' => "cicikmisworowati@gmail.com", 'username' => "cicikmisworowati@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Alfin Nashiha", 'email' => "Pentolsunduk26@gmail.com", 'username' => "Pentolsunduk26@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DISHERA DALUNIAKSA S", 'email' => "disheradnsas@gmail.com", 'username' => "disheradnsas@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Nina Anis Ayu Wulansari", 'email' => "ninaanis1998@gmail.com", 'username' => "ninaanis1998@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANDYA WIDYAARTA", 'email' => "widyaarta420@gmail.com", 'username' => "widyaarta420@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Muji Astuti, S.Pi", 'email' => "astutimn123@gmail.com", 'username' => "astutimn123@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "TRI PURNA NUGROHO", 'email' => "tripurnanugroho@gmail.com", 'username' => "tripurnanugroho@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "IKA YULIA AGUSTINA", 'email' => "ikayuliaagustin@gmail.com", 'username' => "ikayuliaagustin@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ENDRI NURIYANA", 'email' => "arsyarsy596@gmail.com", 'username' => "arsyarsy596@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ELIZABETH DEBORA MONETRY", 'email' => "deboramo1712@gmail.com", 'username' => "deboramo1712@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Nur wahyu choirudin", 'email' => "nuwachoi@gmail.com", 'username' => "nuwachoi@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Abed Nego", 'email' => "Abed120310@gmail.com", 'username' => "Abed120310@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "GALIH CANDRA ANOM MUKTI", 'email' => "galihcandraanommukti@gmail.com", 'username' => "galihcandraanommukti@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ahmad Nur Kholis", 'email' => "ahmadnuurkholis@gmail.com", 'username' => "ahmadnuurkholis@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ramadhan surya unggul pamungkas", 'email' => "Ramasurya235@gmail.com", 'username' => "Ramasurya235@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Kevin Surya Pratama", 'email' => "Kevinsprtm@gmail.com", 'username' => "Kevinsprtm@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Nely Sarfiyatul Murtawiyah", 'email' => "nelysm96@gmail.com", 'username' => "nelysm96@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "OCTAVIA AMMAR RODIANA", 'email' => "octaviarodiana@gmail.com", 'username' => "octaviarodiana@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Indra setyawan", 'email' => "Indra050992.setyawan@gmail.com", 'username' => "Indra050992.setyawan@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Khulimatul Muamanah", 'email' => "khulimatul1008@gmail.com", 'username' => "khulimatul1008@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "FANNY RAHMASARI", 'email' => "Rahmasarifanny170@gmail.com", 'username' => "Rahmasarifanny170@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Agus dwi setiawan", 'email' => "agusdwis5758@gmail.com", 'username' => "agusdwis5758@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Imroatul Habibah", 'email' => "imroatulhabibah04@gmail.com", 'username' => "imroatulhabibah04@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Firda Amalia Yantika", 'email' => "firdaamalia074@gmail.com", 'username' => "firdaamalia074@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ITA NOOR AINI", 'email' => "aini.ita82@gmail.com", 'username' => "aini.ita82@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Puspa Indah Sulistyaningrum", 'email' => "Puspaindah164@gmail.com", 'username' => "Puspaindah164@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Eka Ulfiyatun Khasanah", 'email' => "ekaulfi463@gmail.com", 'username' => "ekaulfi463@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RIZKY SEPTIANINGSIH", 'email' => "abizarfais7@gmail.com", 'username' => "abizarfais7@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PRISTIN WULANDARI", 'email' => "Www.Pristinwulandari@gmail.com", 'username' => "Www.Pristinwulandari@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Juwitasari", 'email' => "Sarijuwita611@gmail.com", 'username' => "Sarijuwita611@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Galantika Windyarini", 'email' => "windyarinigalantika@gmail.com", 'username' => "windyarinigalantika@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NIKEN SAPTIRAHAYU", 'email' => "niken.priyanto@gmail.com", 'username' => "niken.priyanto@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUSANTI", 'email' => "susanfataya86@gmail.com", 'username' => "susanfataya86@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Wilujeng Handayani", 'email' => "wiluyeng23@gmail.com", 'username' => "wiluyeng23@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARIK PUSPITASARI", 'email' => "sari89885@gmail.com", 'username' => "sari89885@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Suparman", 'email' => "masbaim1983@gmail.com", 'username' => "masbaim1983@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Jekky Andriansyah", 'email' => "jeckyandriansyah94@gmail.com", 'username' => "jeckyandriansyah94@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Pianawati", 'email' => "Pianawati1483@gmail.com", 'username' => "Pianawati1483@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "EKA SUSANTI", 'email' => "echaechi400@gmail.com", 'username' => "echaechi400@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Didik Sujarwo", 'email' => "didiksujarwo682@gmail.com", 'username' => "didiksujarwo682@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ILUH AYU ISWOROWATI", 'email' => "iluhayu2905@gmail.com", 'username' => "iluhayu2905@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARIS SETYORINI", 'email' => "arissetyorinivicko@gmail.com", 'username' => "arissetyorinivicko@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RINI HIDAYATI", 'email' => "rinihidayati1977@gmail.com", 'username' => "rinihidayati1977@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Puji Hartono", 'email' => "garonbalerejo27@gmail.com", 'username' => "garonbalerejo27@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RANI PUSPITASARI", 'email' => "ranirara518@gmail.com", 'username' => "ranirara518@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Arie susilo", 'email' => "blere.slalu@gmail.com", 'username' => "blere.slalu@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RIZAL MARTA WICAKSONO", 'email' => "Phonieardiansyah@gmail.com", 'username' => "Phonieardiansyah@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Fitri dewi ristiana", 'email' => "ristidewi00@gmail.com", 'username' => "ristidewi00@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Alfi Rahma Susanti", 'email' => "alfiers04@gmail.com", 'username' => "alfiers04@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANIK SURYANI", 'email' => "suryanianik911@gmail.com", 'username' => "suryanianik911@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AHMAD DHAWAMI", 'email' => "dawameko9a@gmail.com", 'username' => "dawameko9a@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "JULITA ANGGA SARI", 'email' => "julitaanggasari0730@gmail.com", 'username' => "julitaanggasari0730@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SRI WULANDARI", 'email' => "dwidenada1@gmail.com", 'username' => "dwidenada1@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Muchlis Nur Falah", 'email' => "muchlisnf11@gmail.com", 'username' => "muchlisnf11@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "JOKO SUWARNO", 'email' => "Uciemot@gmail.com", 'username' => "Uciemot@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUNARSIH", 'email' => "Sunarsihwijaya0507@gmail.com", 'username' => "Sunarsihwijaya0507@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Shafa Ardhana Riswari", 'email' => "safaardhana549@gmail.com", 'username' => "safaardhana549@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Afilia Nur Rifandhani", 'email' => "nurafilia26@gmail.com", 'username' => "nurafilia26@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "MURDIONO", 'email' => "Chymoenk.30@gmail.com", 'username' => "Chymoenk.30@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NITA ELSA JULIATI", 'email' => "nitaelsa07@gmail.com", 'username' => "nitaelsa07@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NURZANAH", 'email' => "nzanah25@gmail.com", 'username' => "nzanah25@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SEFIDA SETIA HANDANI", 'email' => "sefidafida99@gmail.com", 'username' => "sefidafida99@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Zidna Urvi elmina", 'email' => "zidna123elmina@gmail.com", 'username' => "zidna123elmina@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Depi Nursiati", 'email' => "depinursiati@gmail.com", 'username' => "depinursiati@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LIA MEI SUSANTI", 'email' => "mei24106@gmail.com", 'username' => "mei24106@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AGUS JATMIKO", 'email' => "Agusbandos22@gmail.com", 'username' => "Agusbandos22@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Umy fausiyah", 'email' => "Umyfauziah80@gmail.com", 'username' => "Umyfauziah80@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Farida Ayu Saputri", 'email' => "faridaayusaputri1@gmail.com", 'username' => "faridaayusaputri1@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NUR WIDYA ANGGRAINI", 'email' => "nurwidya927@gmail.com", 'username' => "nurwidya927@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Nurul fauzjiah", 'email' => "annisafitriana336@gmail.com", 'username' => "annisafitriana336@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SOFYAN ANWAR", 'email' => "sofyanwar@gmail.com", 'username' => "sofyanwar@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Fama Dwi Wahyuningsih", 'email' => "famadwi94@gmail.com", 'username' => "famadwi94@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DIFA SATRIA PAMUNGKAS", 'email' => "difasatriapamungkas@gmail.com", 'username' => "difasatriapamungkas@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SAMSUL HADI", 'email' => "keinara101018@gmail.com", 'username' => "keinara101018@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ryan Yuli Purnamawati", 'email' => "ryanyuli89@gmail.com", 'username' => "ryanyuli89@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SUSI RAHAYU", 'email' => "yosirahayu51@gmail.com", 'username' => "yosirahayu51@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Fiska Kholifahtul Muslima", 'email' => "Fiskadinda@gmail.com", 'username' => "Fiskadinda@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SITI RIYADHOTUL NI'MAH WAROHMAH", 'email' => "riyadhotul55@gmail.com", 'username' => "riyadhotul55@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RISMA OKTAFIYANTI", 'email' => "oktafirisma@gmail.com", 'username' => "oktafirisma@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Amirah Hadi", 'email' => "Amirahhadi6@gmail.com", 'username' => "Amirahhadi6@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DINDA EFFI SETYONINGSIH", 'email' => "setyaningsihadinda32@gmail.com", 'username' => "setyaningsihadinda32@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Sofyan Khanafi", 'email' => "sofyankhanafi17@gmail.com", 'username' => "sofyankhanafi17@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Rizky Wahyuliana", 'email' => "Rizkylianawahyu@gmail.com", 'username' => "Rizkylianawahyu@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AHMAD FAIZIN", 'email' => "ahmad.faizin0305@gmail.com", 'username' => "ahmad.faizin0305@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dwi Wahyu Kristanti", 'email' => "dwahyukristanti8@gmail.com", 'username' => "dwahyukristanti8@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yoga dwi cahya putra", 'email' => "yogadwi7652@gmail.com", 'username' => "yogadwi7652@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LUTFIANA NUR AZIZAH", 'email' => "ti.lutfiananura21@gmail.com", 'username' => "ti.lutfiananura21@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Indri Novi Jayanti", 'email' => "indrinovi672@gmail.com", 'username' => "indrinovi672@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Shefani Melinda Ristanti", 'email' => "Shefanimelinda44@gmail.com", 'username' => "Shefanimelinda44@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "devianna intan nur safitri", 'email' => "deviannaintan4@gmail.com", 'username' => "deviannaintan4@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Rezcy Widya Hartanti", 'email' => "rezcywidya26@gmail.com", 'username' => "rezcywidya26@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Tri Wulandari", 'email' => "triw56216@gmail.com", 'username' => "triw56216@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Erisca Nur Ramadhany", 'email' => "eriscaramadhany2020@gmail.com", 'username' => "eriscaramadhany2020@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Sita Hapsari", 'email' => "sitahapsari1717@gmail.com", 'username' => "sitahapsari1717@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "RATIH RISTIANI", 'email' => "mazepris@yahoo.com", 'username' => "mazepris@yahoo.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Siti maesarotin", 'email' => "Maesarotinsiti@gmail.com", 'username' => "Maesarotinsiti@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Muhaimin", 'email' => "muhayd4@gmail.com", 'username' => "muhayd4@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Esti Sriwahyuni", 'email' => "estisriwahyuni19@gmail.com", 'username' => "estisriwahyuni19@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Titin Hasnawati", 'email' => "titnvivanno1207@gmail.com", 'username' => "titnvivanno1207@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ARYANTO WIBOWO", 'email' => "Aryantowibowo1502@gmail.com", 'username' => "Aryantowibowo1502@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ahmad Dimas Setya Aji", 'email' => "ajidimas227@gmail.com", 'username' => "ajidimas227@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dwi Retno Wahyuningtyas", 'email' => "dwiretnowahyuningtyas890@gmail.com", 'username' => "dwiretnowahyuningtyas890@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "KARLINA FITRIA SARI", 'email' => "karinafitria396@gmail.com", 'username' => "karinafitria396@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "LIA TRIWAHYUNI", 'email' => "liafenita58@gmail.com", 'username' => "liafenita58@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "HARIS SRIWAHYUNI", 'email' => "harissriwahyuni2102@gmail.com", 'username' => "harissriwahyuni2102@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "SHINTA NUR AFIFAH", 'email' => "shintanurafifah509@gmail.com", 'username' => "shintanurafifah509@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Andrika Wahyu Wicaksono", 'email' => "andwhysono@gmail.com", 'username' => "andwhysono@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "PAMUJI", 'email' => "haviarprigiantika@gmail.com", 'username' => "haviarprigiantika@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Sinta Anisa", 'email' => "sintaanisa2016@gmail.com", 'username' => "sintaanisa2016@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Friska Tri Diana Sari", 'email' => "friskadiana56@gmail.com", 'username' => "friskadiana56@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dian Agus Susanti", 'email' => "dianagus222222@gmail.com", 'username' => "dianagus222222@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Leni setiyowati", 'email' => "Lenisetiyowati8@gmail.com", 'username' => "Lenisetiyowati8@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ZELIN PUTRI MASITOH", 'email' => "masitohzelin@gmail.com", 'username' => "masitohzelin@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Taufik Setiawan", 'email' => "taufiksempek@gmail.com", 'username' => "taufiksempek@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Aldiansyah Kurnia Ramadhan", 'email' => "aldiansyahkurnia3@gmail.com", 'username' => "aldiansyahkurnia3@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Putri Kemala Sari", 'email' => "putri.kemalaa25@gmail.com", 'username' => "putri.kemalaa25@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Mifta Putri Apriliani", 'email' => "miftaputri199@gmail.com", 'username' => "miftaputri199@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "M. Ichsan Nur Kartabuana", 'email' => "muhamad.ichsan.nur@gmail.com", 'username' => "muhamad.ichsan.nur@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ratna Putri Wardhani", 'email' => "erpewe.1305@gmail.com", 'username' => "erpewe.1305@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Fajrin Saidah", 'email' => "fajrincareer@gmail.com", 'username' => "fajrincareer@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Mayna Fitriya Azai Zirnikh", 'email' => "mayhendrik17@gmail.com", 'username' => "mayhendrik17@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DEASYANA CITRA RAHMADAYANTI", 'email' => "deasyanacitra@gmail.com", 'username' => "deasyanacitra@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Yayuk susanti", 'email' => "Yayuksusanty79@gmail.com", 'username' => "Yayuksusanty79@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "NOVITA YUNI LESTARI", 'email' => "vita220687@gmail.com", 'username' => "vita220687@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "DWI PUJI LESTARI", 'email' => "Hellothary1505@gmail.com", 'username' => "Hellothary1505@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Annisa tri rahmawati", 'email' => "Nisa.rahma48@gmail.com", 'username' => "Nisa.rahma48@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Miftakul Huda", 'email' => "mh1543125@gmail.com", 'username' => "mh1543125@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Devi Sabrina Azmi", 'email' => "devisabrina639@gmail.com", 'username' => "devisabrina639@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Afifah Nurul Izzah", 'email' => "afifahnurulizzah23@gmail.com", 'username' => "afifahnurulizzah23@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "AFINA EKA SEPTI", 'email' => "afinaekasepti@gmail.com", 'username' => "afinaekasepti@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Elmira fara izzati", 'email' => "Elmirafara8@gmail.com", 'username' => "Elmirafara8@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANA MASLIKHAH", 'email' => "anamaslikhah63@gmail.com", 'username' => "anamaslikhah63@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "MUFIDA FAUZIA", 'email' => "mufidafauzia05@gmail.com", 'username' => "mufidafauzia05@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Rina Wulandari", 'email' => "wulandaririna40@gmail.com", 'username' => "wulandaririna40@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Nadia Hasna ‘Aliyyah", 'email' => "nadiahasnaaliyahh2@gmail.com", 'username' => "nadiahasnaaliyahh2@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "defi yunianti", 'email' => "defi.yuni16@gmail.com", 'username' => "defi.yuni16@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Aris Setyo Jarwanto", 'email' => "arismdn74@gmail.com", 'username' => "arismdn74@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Ridho Mahbudin", 'email' => "ridhomahbudin28@gmail.com", 'username' => "ridhomahbudin28@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Kristina Nadila Wijayanti", 'email' => "itin.nadila@gmail.com", 'username' => "itin.nadila@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Refin yusniawati", 'email' => "refin0654@gmail.com", 'username' => "refin0654@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Rudianto", 'email' => "antorudi369@gmail.com", 'username' => "antorudi369@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Dawam krisbyantoro", 'email' => "Dawamkris09@gmail.com", 'username' => "Dawamkris09@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Arnela Novia Larasati", 'email' => "noviarnela02@gmail.com", 'username' => "noviarnela02@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "ANDI SETIAWAN", 'email' => "andisetiawann986@gmail.com", 'username' => "andisetiawann986@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "Lukidzha tatalova almunafa", 'email' => "almunafa0@gmail.com", 'username' => "almunafa0@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
            ['firstname' => "UMAR SYAIFUDIN", 'email' => "udien.p05@gmail.com", 'username' => "udien.p05@gmail.com", 'organization_id' => 3519, 'regency_id' => 3519,],
        ];
        foreach ($users as $user) {
            // check if user exists by email
            if (!User::where('email', $user['email'])->exists()) {
                $u = User::create(['firstname' => $user['firstname'], 'email' => $user['email'], 'regency_id' => $user['regency_id'], 'organization_id' => $user['organization_id'], 'username' => $user['username'], 'password' => Hash::make('se26sukses')]);
                $u->assignRoleAllDatabase('pml');
            }
        }
    }
}
