<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class SidoarjoKdmUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            ['firstname' => "Agus Santoso", 'email' => "agussantoso99a@gmail.com", 'username' => "Agus Santoso", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Lia Fitria", 'email' => "liaaveiro08@gmail.com", 'username' => "Lia Fitria", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Oni Susanto", 'email' => "onipemerintahan@gmail.com", 'username' => "Oni Susanto", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Sunawan", 'email' => "nawan1886@gmail.com", 'username' => "Sunawan", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Ani Rusdiana", 'email' => "anirusdiana0@gmail.com", 'username' => "Ani Rusdiana", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Lina Yuniarti", 'email' => "ditalina052@gmail.com", 'username' => "Lina Yuniarti", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Sasi Mai Aprissiasih", 'email' => "sasimaiaprissiasi@gmail.com", 'username' => "Sasi Mai Aprissiasih", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Susanti Ermawati", 'email' => "susantiermawati@gmail.com", 'username' => "Susanti Ermawati", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Tutik", 'email' => "tutiknk@gmail.com", 'username' => "Tutik", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Al Adawiyah", 'email' => "dawiyahalda39@gmail.com", 'username' => "Al Adawiyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "AMIRUL VARDIANSYAH", 'email' => "amirulvardiansyah01@gmail.com", 'username' => "AMIRUL VARDIANSYAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Dwi Suryaningsih", 'email' => "dwisurya985@gmail.com", 'username' => "Dwi Suryaningsih", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MOHAMAD FAIZUL MUTTAQIN", 'email' => "afandraun@gmail.com", 'username' => "MOHAMAD FAIZUL MUTTAQIN", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "RENNY ISMAWATUR RIDLOH", 'email' => "rerebriseis@gmail.com", 'username' => "RENNY ISMAWATUR RIDLOH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "RIZKA WAHYUNI", 'email' => "rizkawahyuni77@gmail.com", 'username' => "RIZKA WAHYUNI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Ahmad Thoriq Hamdan", 'email' => "ahmadtorick@gmail.com", 'username' => "Ahmad Thoriq Hamdan", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "DWI ELLY NUGRAENI", 'email' => "dwi.elly89@gmail.com", 'username' => "DWI ELLY NUGRAENI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "YUDI MAULANA", 'email' => "bmine12.bm@gmail.com", 'username' => "YUDI MAULANA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Abdulloh mubarok", 'email' => "abdullohmubarok52@gmail.com", 'username' => "Abdulloh mubarok", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Nurul Agus irawan", 'email' => "agusirwan94@gmail.com", 'username' => "Nurul Agus irawan", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Verikah Dwi Windari", 'email' => "verikawindari86@gmail.com", 'username' => "Verikah Dwi Windari", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "FARIDA EVI ANITA", 'email' => "farida.evi91@gmail.com", 'username' => "FARIDA EVI ANITA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "KHOIRUN NISA'", 'email' => "nisa05785@gmail.com", 'username' => "KHOIRUN NISA'", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MOHAMMAD LUMINTU ROCHMAT", 'email' => "lumintur7@gmail.com", 'username' => "MOHAMMAD LUMINTU ROCHMAT", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MUHAMMAD SALSABIL", 'email' => "salsabilmuh002@gmail.com", 'username' => "MUHAMMAD SALSABIL", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NUR LAILIYAH", 'email' => "lailiyah1610@gmail.com", 'username' => "NUR LAILIYAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Farkhatul Kifyati", 'email' => "farkhakif14@gmail.com", 'username' => "Farkhatul Kifyati", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Ida Zulfia", 'email' => "idazulfiah3@gmail.com", 'username' => "Ida Zulfia", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "M Suhartono", 'email' => "moch.hartono17@gmail.com", 'username' => "M Suhartono", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Misuyanto", 'email' => "misuyanto@yahoo.co.id", 'username' => "Misuyanto", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Safarid", 'email' => "safarid77@gmail.com", 'username' => "Safarid", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Saniyah", 'email' => "saniyahsubekti605@gmail.com", 'username' => "Saniyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Santi Kurniawati", 'email' => "santikurniawati26@gmail.com", 'username' => "Santi Kurniawati", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Siti Chomariyah", 'email' => "siti.chomariyah014@gmail.com", 'username' => "Siti Chomariyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Sudarsono", 'email' => "wanicoba76@gmail.com", 'username' => "Sudarsono", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Vita Wahyu Permata", 'email' => "Vitapermata644@gmail.com", 'username' => "Vita Wahyu Permata", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "AL MAR'ATUS SOLIKHAH", 'email' => "aal.almaratus@gmail.com", 'username' => "AL MAR'ATUS SOLIKHAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "FARIDAH", 'email' => "faridahayid30@gmail.com", 'username' => "FARIDAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "IMROATUL AZIZAH", 'email' => "imroatulazizah1975@gmail.com", 'username' => "IMROATUL AZIZAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "JULI ARDIANSAH", 'email' => "juliardiansah0107@gmail.com", 'username' => "JULI ARDIANSAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MONALISA OCTAVIA", 'email' => "viani.2914@gmail.com", 'username' => "MONALISA OCTAVIA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NURHADI", 'email' => "noenghadi@gmail.com", 'username' => "NURHADI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "TEGUH ARDIANTO", 'email' => "Teguhardianto58@gmail.com", 'username' => "TEGUH ARDIANTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "WAHYU RAMADHAN", 'email' => "widiwahyu829@gmail.com", 'username' => "WAHYU RAMADHAN", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "YULI KRISTANTO", 'email' => "yulikris1987@gmail.com", 'username' => "YULI KRISTANTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ACHMAD ARIF SUCIPTO", 'email' => "Achmadarifsucipto@gmail.com", 'username' => "ACHMAD ARIF SUCIPTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ANITA SULANDARI", 'email' => "anitasulandari1999@gmal.com", 'username' => "ANITA SULANDARI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "FERI SURYA ERLANGGA", 'email' => "feri.s.erlangga@gmail.com", 'username' => "FERI SURYA ERLANGGA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MUSTICHA VIVIEN", 'email' => "musticha.vivien.22@gmail.com", 'username' => "MUSTICHA VIVIEN", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NURUL ISTI'ANAH", 'email' => "istianahnurul14@gmail.com", 'username' => "NURUL ISTI'ANAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Aprillia Tri kewinda ratnasari", 'email' => "ericzpapacila@gmail.com", 'username' => "Aprillia Tri kewinda ratnasari", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "EKO MUKTI WIBOWO", 'email' => "echomukti11@gmail.com", 'username' => "EKO MUKTI WIBOWO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Izza Wardatul Mufidah", 'email' => "izzawardah7@gmail.com", 'username' => "Izza Wardatul Mufidah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "LUTFI HADIYANTO", 'email' => "renaanggun1602@gmail.com", 'username' => "LUTFI HADIYANTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MARIA ULFAH", 'email' => "mariaadis13@gmail.com", 'username' => "MARIA ULFAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NONO TEGUH SUSANTO", 'email' => "lunglinagakecil@gmail.com", 'username' => "NONO TEGUH SUSANTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NUR LAILYANNA BISRI", 'email' => "laily.nur85@gmail.com", 'username' => "NUR LAILYANNA BISRI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "SITI MARIA ULFAH", 'email' => "ulfahazzam2@gmail.com", 'username' => "SITI MARIA ULFAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "THIESNA LUZZIANTIE", 'email' => "luzzianthiesna@gmail.com", 'username' => "THIESNA LUZZIANTIE", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Anis Hardiyanti", 'email' => "anishardiyanti096@gmail.com", 'username' => "Anis Hardiyanti", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ELI WAHJUNIJATI", 'email' => "elywahyuniati@gmail.com", 'username' => "ELI WAHJUNIJATI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Ida Sulistyorini", 'email' => "Idasulis45@gmail.com", 'username' => "Ida Sulistyorini", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Isrofatin Miftakhul visa auliah", 'email' => "Isrofatinauliah@gmail.com", 'username' => "Isrofatin Miftakhul visa auliah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MIRZA VIONA RAHMATINA", 'email' => "mirzavior@gmail.com", 'username' => "MIRZA VIONA RAHMATINA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Muhammad Aswin Albian", 'email' => "muhammadaa08@gmail.com", 'username' => "Muhammad Aswin Albian", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Qonita zeldia (Sifian Hayu)", 'email' => "zelzeta@gmail.com", 'username' => "Qonita zeldia (Sifian Hayu)", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "RAMADHANY SULISTYANTO", 'email' => "dhanzka@gmail.com", 'username' => "RAMADHANY SULISTYANTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "SALWA JULLANAR FADHILAH", 'email' => "salwajullanar01@gmail.com", 'username' => "SALWA JULLANAR FADHILAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Siti Halimatus Sa'diyah", 'email' => "shalimatus409@gmail.com", 'username' => "Siti Halimatus Sa'diyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "YASINTA JULIAN DWI KRISTARIA", 'email' => "yasintajuliandk@gmail.com", 'username' => "YASINTA JULIAN DWI KRISTARIA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Yohanes", 'email' => "yohanesyohanes8@gmail.com", 'username' => "Yohanes", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Ira Mirasari", 'email' => "iramirasari60@gmail.com", 'username' => "Ira Mirasari", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NAKHNUL HUSIN", 'email' => "niyanakhnul77@gmail.com", 'username' => "NAKHNUL HUSIN", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NUNUNG ANGGRAINI", 'email' => "anggraininunung82@gmail.com", 'username' => "NUNUNG ANGGRAINI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Rhina Kuswanti", 'email' => "rhina.kuswanti@gmail.com", 'username' => "Rhina Kuswanti", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Sriyani", 'email' => "sriyani110384@gmail.com", 'username' => "Sriyani", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ARIZAL RAHMAN PURWANTO", 'email' => "Arizalrahman694@gmail.com", 'username' => "ARIZAL RAHMAN PURWANTO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Jatmico Bimo Anugro", 'email' => "cybermeong294@gmail.com", 'username' => "Jatmico Bimo Anugro", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MOH.THORIQ FIRDAUS", 'email' => "emailkudewe1234567890@gmail.com", 'username' => "MOH.THORIQ FIRDAUS", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "SILVIA NISWATUL ROHMAH", 'email' => "silvia.niswatul@gmail.com", 'username' => "SILVIA NISWATUL ROHMAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "SRI ROCHMIYATI", 'email' => "srirochmiyati1@gmail.com", 'username' => "SRI ROCHMIYATI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "WIKE AFRIANTI", 'email' => "wikeafrianti467@gmail.com", 'username' => "WIKE AFRIANTI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ACHMAD SOLIK", 'email' => "achmadsolik6363@gmail.com", 'username' => "ACHMAD SOLIK", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ADAM ISMAIL", 'email' => "asek.asekk@gmail.com", 'username' => "ADAM ISMAIL", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "AHMAD SABARUDIN", 'email' => "ahmadsabarudin77@gmail.com", 'username' => "AHMAD SABARUDIN", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "INGE INDRAWATI", 'email' => "ingeindrawati73@gmail.com", 'username' => "INGE INDRAWATI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "M. WASIS SUSANTO. ST", 'email' => "wasissusanto1969@gmail.com", 'username' => "M. WASIS SUSANTO. ST", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MOCH SAMSUL HUDA", 'email' => "sarmilikin@gmail.com", 'username' => "MOCH SAMSUL HUDA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Moh. Su'udi", 'email' => "muhammadsuudi20@gmail.com", 'username' => "Moh. Su'udi", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "MOHAMMAD ANSHOR", 'email' => "muhammadanshor71@gmail.com", 'username' => "MOHAMMAD ANSHOR", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "NURUL FITRI", 'email' => "nurulfitripurwadi@gmail.com", 'username' => "NURUL FITRI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "SUSILO", 'email' => "swaluyo162@gmail.com", 'username' => "SUSILO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "FAUZIAH DEWI", 'email' => "fauziahdewi861@gmail.com", 'username' => "FAUZIAH DEWI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "HENI KRISWANTI", 'email' => "henikriswanti12@gmail.com", 'username' => "HENI KRISWANTI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "IKA RINDRA LENI YUWONO", 'email' => "ikarindralenyyuwono.ir@gmail.com", 'username' => "IKA RINDRA LENI YUWONO", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "KARTIANI", 'email' => "aanik9181@gmail.com", 'username' => "KARTIANI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "LAILATUL KHUMAIDAH", 'email' => "khumaidahlailatul@gmail.com", 'username' => "LAILATUL KHUMAIDAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "SRI YULIATI", 'email' => "yulioso427@gmail.com", 'username' => "SRI YULIATI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "TRI WAHYUNI", 'email' => "wahyuni06tri@gmail.com", 'username' => "TRI WAHYUNI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Adhy Zahirotul Lu'aliyah", 'email' => "ady.zahirotul@gmail.com", 'username' => "Adhy Zahirotul Lu'aliyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Dewi Rahmah Lutfiani", 'email' => "dhewirahmah321@gmail.com", 'username' => "Dewi Rahmah Lutfiani", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Dyan Karya kristiani", 'email' => "dyankarya5@gmail.com", 'username' => "Dyan Karya kristiani", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Evi Novitasari", 'email' => "evinovita07sari@gmail.com", 'username' => "Evi Novitasari", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Jumiran", 'email' => "Jumiran.pertapan@gmail.com", 'username' => "Jumiran", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Miftahul Ulum", 'email' => "soehagink26@gmail.com", 'username' => "Miftahul Ulum", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Mohammad Anggil Satriawan", 'email' => "anggilsat@gmail.com", 'username' => "Mohammad Anggil Satriawan", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Novalinda Rahmayanti", 'email' => "rahmayantinovalinda@gmail.com", 'username' => "Novalinda Rahmayanti", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Rizki Azizah Malik", 'email' => "rizkiazizah.ra@gmail.com", 'username' => "Rizki Azizah Malik", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Setiyo Dwi Wulandari", 'email' => "Wulan_dari_89@yahoo.com", 'username' => "Setiyo Dwi Wulandari", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Wiwin Choiriyah", 'email' => "wiwin.choiriyah@gmail.com", 'username' => "Wiwin Choiriyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ACHMAD RIZAL", 'email' => "achmadrizal301@gmail.com", 'username' => "ACHMAD RIZAL", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Achmad Wahyu Surya Wahono", 'email' => "arjunohono@gmail.com", 'username' => "Achmad Wahyu Surya Wahono", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "IKA SURYANINGRUM", 'email' => "ikasuryafadli@gmail.com", 'username' => "IKA SURYANINGRUM", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "IVA AGUSTINA", 'email' => "ivaagustin80@gmail.com", 'username' => "IVA AGUSTINA", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "KASTUNIK", 'email' => "kastunik75nanok@gmail.com", 'username' => "KASTUNIK", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "LUCY HARYATI", 'email' => "loecyharyati@gmail.com", 'username' => "LUCY HARYATI", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Rika budiarti", 'email' => "Rikabudiarti89@gmail.com", 'username' => "Rika budiarti", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "ALIVIA RIFANATUL BADRIYAH", 'email' => "alifiarifa1988@gmail.com", 'username' => "ALIVIA RIFANATUL BADRIYAH", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Qoni'atur Rodhiyah", 'email' => "qoniks.pi.97@gmail.com", 'username' => "Qoni'atur Rodhiyah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Siti Rokhimah", 'email' => "srokhimah57@gmail.com", 'username' => "Siti Rokhimah", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Sugeng Hariyanto", 'email' => "bogempgr@gmail.com", 'username' => "Sugeng Hariyanto", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Sunarmi", 'email' => "isunarmi2@gmail.com", 'username' => "Sunarmi", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
            ['firstname' => "Wahyu Sari Purnami", 'email' => "gladisnoor@gmail.com", 'username' => "Wahyu Sari Purnami", 'password' => Hash::make('se26sukses'), 'organization_id' => 3515, 'regency_id' => 3515,],
        ];

        foreach ($users as $user) {
            // check if user exists by email
            if (!User::where('email', $user['email'])->exists()) {
                $u = User::create([
                    'firstname' => $user['firstname'],
                    'email' => $user['email'],
                    'regency_id' => $user['regency_id'],
                    'organization_id' => $user['organization_id'],
                    'username' => $user['username'],
                    'password' => Hash::make('se26sukses'),
                    'is_kendedes_user' => true
                ]);
                $u->assignRoleAllDatabase('pml');
            }
        }
    }
}
