services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: directory-app-laravel-image
    container_name: directory-app
    networks:
      - laravel_network
    ports:
      - "8888:8000"
    entrypoint: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    volumes:
      - ./docker/php/php-prod.ini:/usr/local/etc/php/php.ini
      - ./backup:/var/www/backup
      - storagedata:/var/www/storage/app
      - geojson:/var/www/python_script/geojson
      # - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: directory-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_MAIN_DATABASE}
      MYSQL_USER: ${DB_MAIN_USERNAME}
      MYSQL_PASSWORD: ${DB_MAIN_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MAIN_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./backup:/var/www/backup
      # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3310:3306"
    networks:
      - laravel_network

  redis:
    container_name: directory-app-redis
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    networks:
      - laravel_network

  # redis-client:
  #   container_name: directory-app-redis-client
  #   image: redis
  #   networks:
  #     - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  storagedata:
    driver: local
  geojson:
    driver: local
