services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: laravel_app
    container_name: directory-app
    networks:
      - laravel_network    
    ports:
      - "8888:8000"
    # ports:
    #   - "8085:8000"

  # web:
  #   image: nginx:alpine
  #   container_name: directory-app-web
  #   restart: unless-stopped
  #   ports:
  #     - "8888:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - laravel_network
  #   depends_on:
  #     - app

  db:
    image: mysql:8.0
    container_name: directory-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local